import { auth, db, isAdminEmail } from "./firebase-config.js";
import { isMemberActive } from "./member-access.js";
import { staticArticles } from "./static-articles.js?v=20260728-restore-articles-2";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { collection, doc, getDoc, getDocs, query, runTransaction, serverTimestamp, where } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const categoryLabels = { spiritual: "靈．修行", worldly: "人．俗世", "spirit-world": "異．靈界", reading: "思．讀物" };
const root = document.getElementById("article-root");
const tabs = document.getElementById("category-tabs");
const params = new URLSearchParams(location.search);
const activeCategory = params.get("category") || "";
const activeAccess = params.get("access") || "all";
const activeId = params.get("id") || "";
const memberMarker = "<!-- member-only -->";
const paidMarker = "<!-- paid-only -->";
const bookUrl = "https://lyyuan.tw/books.html?v=spiritual-books-20260703-refresh";
const limitedReadingDeadlines = new Map([
  ["japan-temple-faith-and-decline", Date.parse("2026-07-28T15:15:12.000Z")],
  ["shenming-yinlu-ganying-budengyu-xiuwei", Date.parse("2026-07-28T10:30:00.000Z")],
  ["good-fortune-believe-in-yourself-choices", Date.parse("2026-07-26T16:19:35.857Z")],
  ["jitong-shenming-fushen", Date.parse("2026-07-24T22:28:58.068Z")],
  ["market-crash-money-self-control", Date.parse("2026-07-24T01:00:00.000Z")]
]);
const articleGuides = {};
const articleThumbnailImages = {};
const articleHooks = {};
let loadedArticles = [];
let articleMetrics = new Map();
let currentUser = null;
let currentMemberAccess = null;
let visibleArticleCount = window.matchMedia("(max-width: 760px)").matches ? 6 : 9;

function escapeHtml(value = "") { return String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char])); }
function renderInline(value = "") { return escapeHtml(value).replace(/!\[([^\]]*)\]\(([^)\s]+)\)/g, '<img src="$2" alt="$1">'); }
function renderContent(value = "") { return value.replace(memberMarker, "").replace(paidMarker, "").split(/\n{2,}/).map((block) => { const trimmed = block.trim(); if (!trimmed) return ""; if (trimmed.startsWith("### ")) return `<h3>${renderInline(trimmed.slice(4))}</h3>`; if (trimmed.startsWith("## ")) return `<h2>${renderInline(trimmed.slice(3))}</h2>`; if (trimmed.startsWith("# ")) return `<h1>${renderInline(trimmed.slice(2))}</h1>`; return `<p>${renderInline(trimmed).replace(/\n/g, "<br>")}</p>`; }).join(""); }
function getTimeValue(value) { if (!value) return 0; if (typeof value?.toMillis === "function") return value.toMillis(); if (typeof value === "number") return value; const parsed = Date.parse(value); return Number.isNaN(parsed) ? 0 : parsed; }
function sortPublished(a, b) { return (getTimeValue(b.publishedAt) || getTimeValue(b.updatedAt)) - (getTimeValue(a.publishedAt) || getTimeValue(a.updatedAt)); }
function articleKey(article = {}) { return article.id || article.slug || ""; }
function articleIsPaid(article = {}) { return article.accessType === "paid" || (article.content || "").includes(paidMarker); }
function articleIsLimitedOpen(article = {}) { const key = articleKey(article); return articleIsPaid(article) && limitedReadingDeadlines.has(key) && Date.now() < limitedReadingDeadlines.get(key); }
function articleAccess(article = {}) { return articleIsPaid(article) && !articleIsLimitedOpen(article) ? "paid" : "free"; }
function filterHref(access, category) { const next = new URLSearchParams(); if (access && access !== "all") next.set("access", access); if (category) next.set("category", category); return next.toString() ? `articles.html?${next}` : "articles.html"; }
function renderTabs() { const accessItems = [["all", "全部文章"], ["free", "免費閱讀"], ["paid", "會員閱讀"]]; const categoryItems = [["", "全部主題"], ...Object.entries(categoryLabels)]; const counts = loadedArticles.reduce((result, article) => { result.all += 1; result[articleAccess(article)] += 1; return result; }, { all: 0, free: 0, paid: 0 }); tabs.innerHTML = `<div class="article-filter-panel" id="article-filters"><div class="filter-heading"><strong>選擇想閱讀的文章</strong><span>依閱讀方式或主題快速尋找</span></div><div class="filter-row access-filter" aria-label="閱讀方式">${accessItems.map(([key,label])=>`<a class="${key===activeAccess?"is-active":""}" href="${filterHref(key,activeCategory)}">${label}<small>${counts[key]}</small></a>`).join("")}</div><div class="filter-row topic-filter" aria-label="文章主題">${categoryItems.map(([key,label])=>`<a class="${key===activeCategory?"is-active":""}" href="${filterHref(activeAccess,key)}">${label}</a>`).join("")}</div></div>`; }
function metricValue(articleId, key) { return Number(articleMetrics.get(articleId)?.[key] || 0); }
function renderMetricSummary(articleId, compact = false) { return `<div class="article-engagement${compact?" is-compact":""}" data-metric-article="${escapeHtml(articleId)}"><span>閱讀 <b data-metric-value="views">${metricValue(articleId,"views").toLocaleString("zh-TW")}</b></span><span>分享 <b data-metric-value="shares">${metricValue(articleId,"shares").toLocaleString("zh-TW")}</b></span><span>複製 <b data-metric-value="copies">${metricValue(articleId,"copies").toLocaleString("zh-TW")}</b></span></div>`; }
function getArticleGuide(article = {}) { return articleGuides[articleKey(article)] || { topics: Array.isArray(article.topics) ? article.topics : [], level: article.readingLevel || "" }; }
function getArticleThumbnail(article = {}) { return articleThumbnailImages[articleKey(article)] || article.coverImage || ""; }
function getArticleHook(article = {}) { return articleHooks[articleKey(article)] || article.excerpt || ""; }
function renderArticleGuide(article, compact = false) { const guide = getArticleGuide(article); if (!guide.topics.length && !guide.level) return ""; return `<div class="article-guide${compact?" is-compact":""}" aria-label="文章主題與閱讀程度">${guide.topics.map((topic)=>`<span class="article-topic">${escapeHtml(topic)}</span>`).join("")}${guide.level?`<span class="article-level">${escapeHtml(guide.level)}閱讀</span>`:""}</div>`; }
function renderNextReading() { return ""; }
async function loadArticleMetrics() { try { const snapshot=await getDocs(collection(db,"articleMetrics")); articleMetrics=new Map(snapshot.docs.map((item)=>[item.id,item.data()])); } catch(error){ console.warn("文章統計暫時無法載入。",error); articleMetrics=new Map(); } }
async function incrementArticleMetric(articleId, metric) { if(!articleId||!["views","shares","copies"].includes(metric)) return; const metricRef=doc(db,"articleMetrics",articleId); try { await runTransaction(db,async(transaction)=>{ const snapshot=await transaction.get(metricRef); const current=snapshot.exists()?snapshot.data():{}; transaction.set(metricRef,{articleId,views:Number(current.views||0)+(metric==="views"?1:0),shares:Number(current.shares||0)+(metric==="shares"?1:0),copies:Number(current.copies||0)+(metric==="copies"?1:0),updatedAt:serverTimestamp()}); }); } catch(error){ console.warn(`文章${metric}統計寫入失敗。`,error); } }
function trackArticleView(articleId){ const key=`lyyuan-article-viewed:${articleId}`; try{ if(sessionStorage.getItem(key)) return; sessionStorage.setItem(key,"1"); }catch{} incrementArticleMetric(articleId,"views"); }
function renderLimitedReadingCountdown(){ return ""; }
function bindLimitedReadingCountdowns(){}
function renderList(articles){ const filtered=articles.filter((article)=>(!activeCategory||article.category===activeCategory)&&(activeAccess==="all"||articleAccess(article)===activeAccess)); if(!filtered.length){root.innerHTML='<div class="empty">目前沒有符合條件的文章，請選擇其他分類。</div>';return;} const visible=filtered.slice(0,visibleArticleCount),remaining=filtered.length-visible.length; root.innerHTML=`<div class="article-result-summary"><span>共 ${filtered.length} 篇文章</span><a href="#article-filters">重新選擇分類</a></div><div class="article-grid">${visible.map((article)=>{const key=articleKey(article),access=articleAccess(article),label=access==="paid"?"會員閱讀":articleIsLimitedOpen(article)?"限時免費":"免費閱讀";return `<a class="article-card" data-article-id="${escapeHtml(key)}" href="articles.html?id=${encodeURIComponent(key)}"><div class="article-card-media">${getArticleThumbnail(article)?`<img src="${escapeHtml(getArticleThumbnail(article))}" alt="" loading="lazy" decoding="async">`:'<div class="article-card-placeholder" aria-hidden="true">靈元院文選</div>'}<div class="article-card-media-gradient" aria-hidden="true"></div></div><div class="article-card-content"><div class="article-card-heading"><div class="article-meta">${categoryLabels[article.category]||"文選"}</div><span class="article-access-badge is-${access}">${label}</span></div><h2 class="article-list-title">${escapeHtml(article.title||"未命名文章")}</h2>${renderArticleGuide(article,true)}<p class="article-hook">${escapeHtml(getArticleHook(article))}</p>${renderMetricSummary(key,true)}</div></a>`;}).join("")}</div>${remaining>0?`<div class="article-load-more-wrap"><button class="article-load-more" id="article-load-more" type="button">顯示更多文章 <small>尚有 ${remaining} 篇</small></button></div>`:""}`; document.getElementById("article-load-more")?.addEventListener("click",()=>{visibleArticleCount+=window.matchMedia("(max-width: 760px)").matches?6:9;renderList(articles);}); }
function hasPaidAccess(){
  if (isAdminEmail(currentUser?.email)) return true;
  if (!isMemberActive(currentMemberAccess)) return false;
  const level = currentMemberAccess?.memberLevel || currentMemberAccess?.level;
  return level === "lingji" || currentMemberAccess?.articleAccess === true;
}
function splitMemberContent(content="",articleId=""){ const deadline=limitedReadingDeadlines.get(articleId); if(content.includes(paidMarker)&&deadline&&Date.now()<deadline) return {publicContent:content.replace(paidMarker,""),lockedContent:"",accessType:"open"}; const accessType=content.includes(paidMarker)?"paid":content.includes(memberMarker)?"member":"open"; if(accessType==="paid"&&hasPaidAccess()) return {publicContent:content.replace(paidMarker,""),lockedContent:"",accessType:"open"}; if(accessType==="open") return {publicContent:content,lockedContent:"",accessType}; const marker=accessType==="paid"?paidMarker:memberMarker; const [publicContent,...rest]=content.split(marker); return {publicContent:publicContent.trim(),lockedContent:rest.join(marker).trim(),accessType}; }
async function loadMemberAccess(user){currentMemberAccess=null;if(!user?.email||isAdminEmail(user.email))return;try{const email=user.email.trim().toLowerCase();const snapshot=await getDoc(doc(db,"memberAccess",email));if(snapshot.exists())currentMemberAccess=snapshot.data();}catch(error){console.warn("會員閱讀資格暫時無法確認。",error);}}
function renderBookCta(){return `<div class="article-book-link-wrap"><a class="article-book-link" href="${bookUrl}">延伸閱讀｜宇色靈修著作</a></div>`;}
function renderSupportGate(lockedContent=""){const preview=lockedContent.trim()||"更多宇色老師的靈修解析與生命觀察。";return `<section class="member-lock-zone" id="article-support-gate" aria-label="支持宇色老師"><div class="article-body member-lock-preview" aria-hidden="true">${renderContent(preview)}</div><div class="member-lock-card article-support-card"><div class="member-lock-icon" aria-hidden="true">◇</div><h3>文章未完，繼續閱讀</h3><p>若這篇文章對你有所啟發，歡迎訂閱<br><span>YouTube、追蹤 Facebook，持續收到新的靈修解析。</span></p><div class="article-support-actions"><a class="article-support-link youtube" href="https://www.youtube.com/@lyyuan03" target="_blank" rel="noopener noreferrer">訂閱 靈元院YouTube</a><a class="article-support-link facebook" href="https://www.facebook.com/share/18zfvhPkBF/?mibextid=wwXIfr" target="_blank" rel="noopener noreferrer">追蹤 靈元院 Facebook</a></div><button id="article-continue-button" type="button">繼續閱讀全文</button></div></section>`;}
function renderPaidGate(article){const subject=encodeURIComponent(`詢問付費閱讀｜${article.title||"靈元院文選"}`),body=encodeURIComponent(`您好，我想詢問〈${article.title||"這篇文章"}〉的付費閱讀方式。`);return `<section class="member-lock-zone paid-lock-zone" aria-label="會員專屬"><div class="paid-lock-preview" aria-hidden="true"><span></span><span></span><span></span><span></span><span></span><span></span></div><div class="member-lock-card paid-lock-card"><div class="member-lock-icon" aria-hidden="true">◇</div><h3>本文為付費文章</h3><p>一般會員的影片權益不受影響；付費文章需由後台另外開通。單筆消費滿 NT$15,000 或靈極會員，在有效會期內可登入閱讀全文。</p><div class="paid-inquiry-actions"><button class="paid-inquiry-primary" id="article-member-login-button" type="button">${currentUser?"重新確認閱讀資格":"會員登入"}</button><a class="paid-inquiry-primary" href="https://t.me/lyyuan" target="_blank" rel="noopener noreferrer">詢問閱讀方式</a><a class="paid-inquiry-secondary" href="mailto:lyyuan03@gmail.com?subject=${subject}&body=${body}">使用 Email 詢問</a></div><small>請使用登記的 Gmail 登入</small></div></section>`;}
function bindPaidLogin(){document.getElementById("article-member-login-button")?.addEventListener("click",()=>document.getElementById("member-login-button")?.click());}
function bindArticleContinue(){const button=document.getElementById("article-continue-button"),gate=document.getElementById("article-support-gate"),remaining=document.getElementById("article-remaining-content");if(!button||!gate||!remaining)return;button.addEventListener("click",()=>{gate.remove();remaining.hidden=false;remaining.scrollIntoView({behavior:"smooth",block:"start"});});}
function renderArticleShare(){ return ""; }
function bindArticleShare(){}
function renderCurrentView(){ const article=loadedArticles.find((item)=>articleKey(item)===activeId); if(!article){root.innerHTML='<div class="empty">找不到這篇文章。</div>';return;} const key=articleKey(article); const split=splitMemberContent(article.content||"",key); root.innerHTML=`<article class="article-view"><div class="article-meta">${categoryLabels[article.category]||"文選"}</div><h1>${escapeHtml(article.title||"未命名文章")}</h1><div class="article-body">${renderContent(split.publicContent)}</div>${split.accessType==="paid"?renderPaidGate(article):split.accessType==="member"?renderSupportGate(split.lockedContent):""}${renderBookCta()}</article>`; bindPaidLogin(); bindArticleContinue(); trackArticleView(key); }
async function loadArticles(){ let remote=[]; try{const snapshot=await getDocs(query(collection(db,"articles"),where("status","==","published")));remote=snapshot.docs.map((item)=>({id:item.id,...item.data()}));}catch(error){console.warn("文章資料暫時無法載入。",error);} const merged=new Map(staticArticles.map((item)=>[articleKey(item),item])); remote.forEach((item)=>merged.set(articleKey(item),item)); loadedArticles=[...merged.values()].sort(sortPublished); renderTabs(); if(activeId) renderCurrentView(); else renderList(loadedArticles); }
onAuthStateChanged(auth,async(user)=>{currentUser=user;await loadMemberAccess(user);if(loadedArticles.length&&activeId)renderCurrentView();});
Promise.all([loadArticleMetrics(),loadArticles()]);